name: shap_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - pandas=1.5.3
  - jupyterlab=3.6.1
  - pyarrow=11.0.0
  - scikit-learn=1.2.1
  - glum=2.4.0
  - lightgbm=3.3.5
  - shap=0.41.0
  - pip=23.0
  - matplotlib=3.7.0
  - pip:
    - nb-black==1.0.7
    - tensorflow-cpu==2.11